### ISSUE TITLE
Why create a PagerAdapter

### ISSUE THREAD

**Issue by andykwoods** [noundla/Sunny_Projects#2]
Hi, 

I am thinking of using you view pager implementation in a project. It seems to be pretty solid. I am wondering why you created a PagerAdapter class. I can't see any difference with it and the framework PagerAdapter: https://github.com/android/platform_frameworks_support/blob/master/v4/java/android/support/v4/view/PagerAdapter.java

**Comment by noundla** [comment]
I tried with the PagerAdapter which is avialable in support v4 lib. However, I got few errors while compiling the code. Due to that, I created the PagerAdapter in this. I am not working on this now. Please let me know if you are able to work good without that. :)

P.S: There is no difference between those PagerAdapter s.

**Comment by andykwoods** [comment]
I removed your PagerAdapter and use the lib with the support jar one with no issue. Thanks, Andy.
